# Generated by Django 4.1.1 on 2022-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('JPY', 'jpy')], default='USD', max_length=50, verbose_name='Валюта'),
        ),
    ]
