# Generated by Django 4.1.1 on 2022-09-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0005_discount_order_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='налог')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxs',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_app.tax'),
        ),
    ]
